### ISSUE TITLE
Move BioMuta and BioXpress Read The Docs Documentation to the respective portals on Hive lab

### ISSUE THREAD

**Issue by jeet-vora** [GW-HIVE/biomuta-old#3]
Move BioMuta and BioXpress Read The Docs Documentation to the respective portals on Hive lab
Update when pipeline is modified or changed.

**Comment by mariacuria** [comment]
Asked @Reeya123 for space on HIVE lab where I could put the docs.

**Comment by mariacuria** [comment]
@Reeya123 will create a page for BioXpress similar to the [BioMuta](https://hivelab.biochemistry.gwu.edu/bioMutaReadme) page and its [readme](https://hivelab.biochemistry.gwu.edu/biomuta_readme) since it doesn't have one at the moment. The documentation will have its own page on the website with a link provided on the main BioMuta or BioXpress page. I will provide content for it, and any changes in both documentation will be communicated.

**Comment by mariacuria** [comment]
@rajamazumder wants all the documentation, including BioMuta and BioXpress, on a new [wiki](https://wiki.hivelab.biochemistry.gwu.edu/). As per the scripting_pool slack channel, Hadley or Dacian will set it up. Then we can move the documentation there.

**Comment by mariacuria** [comment]
@HadleyKing here are the links to the [BioMuta](https://biomuta.readthedocs.io/en/latest/#) and [BioXpress](https://bioxpress.readthedocs.io/en/latest/) documentation - those are supposed to be on the wiki.

Conversation from scripting_pool for reference:
<img width="1021" alt="Screenshot 2024-09-19 at 10 23 38" src="https://github.com/user-attachments/assets/f9eaefa9-369d-45b2-ae45-18874cfcd33f">

**Comment by Reeya123** [comment]
@mariacuria From my understanding, Hadley will only assist in setting up the url domain for the wiki space. We will have to take care of the document migration and keep it organized and up to date. 

@HadleyKing Please confirm the above and let us know when you are done setting up the wiki space. Thanks.

**Comment by mariacuria** [comment]
The wiki has been set up: [link](https://hivelab.biochemistry.gwu.edu/wiki/)

I will create documentation pages there.

**Comment by Reeya123** [comment]
Biomuta documentation has been migrated to wiki.

**Comment by Reeya123** [comment]
Bioxpress pipeline documentation has been migrated to wiki
